# Generated by Django 3.0.3 on 2020-04-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_characteristic',
            old_name='patient_id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='patient_id',
            new_name='pid',
        ),
    ]
