# Generated by Django 3.0.3 on 2020-04-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200414_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_mpi',
            name='cha_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient_characteristic'),
        ),
    ]
