# Generated by Django 3.0.3 on 2020-04-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20200414_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_mpi',
            old_name='cha_id',
            new_name='char_id',
        ),
    ]
