# Generated by Django 3.0.3 on 2020-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20200507_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_info',
            name='date2',
            field=models.CharField(default='2020-05-23 18:25:24.396772+07:00', max_length=40),
        ),
        migrations.AlterField(
            model_name='patient_info',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
