# Generated by Django 3.0.3 on 2020-05-23 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200523_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_info',
            name='date2',
        ),
    ]
